# Generated by Django 3.2.19 on 2023-06-16 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_project_list_project_msg_project_ooc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project_Ooc',
            new_name='Project_Doc',
        ),
        migrations.RenameField(
            model_name='project_msg',
            old_name='project_id',
            new_name='project',
        ),
    ]
