# Generated by Django 3.2.19 on 2023-06-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20230616_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_doc',
            old_name='project_id',
            new_name='project',
        ),
        migrations.AddField(
            model_name='project_msg',
            name='namespace',
            field=models.CharField(default='xxx', max_length=64, verbose_name='命名空间'),
        ),
    ]
