# Generated by Django 3.2.19 on 2023-06-19 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20230616_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_msg',
            name='namespace',
            field=models.CharField(max_length=64, verbose_name='命名空间'),
        ),
    ]
