# Generated by Django 3.2.19 on 2023-06-19 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_alter_project_msg_namespace'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project_Doc',
            new_name='Project_ooc',
        ),
    ]
