# Generated by Django 3.2.19 on 2023-06-19 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_rename_project_doc_project_ooc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project_ooc',
            new_name='Project_Doc',
        ),
    ]
