# Generated by Django 3.2.19 on 2023-06-19 02:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_rename_project_ooc_project_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_doc',
            name='doc_time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='修改时间'),
            preserve_default=False,
        ),
    ]
