# Generated by Django 3.2.19 on 2023-06-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_project_doc_doc_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_doc',
            name='doc_time',
            field=models.DateTimeField(verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='project_doc',
            name='project_doc',
            field=models.FileField(null=True, upload_to='upload_files', verbose_name='项目文件'),
        ),
    ]
