# Generated by Django 3.2.19 on 2023-06-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_alter_project_doc_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_doc',
            name='doc_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='修改时间'),
        ),
    ]
