# Generated by Django 3.2.19 on 2023-06-19 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_alter_project_doc_doc_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_doc',
            name='doc_time',
        ),
        migrations.AlterField(
            model_name='project_doc',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.project_list', verbose_name='项目名'),
        ),
        migrations.AlterField(
            model_name='project_doc',
            name='project_doc',
            field=models.FileField(upload_to='upload_files', verbose_name='项目文件'),
        ),
    ]
