# Generated by Django 3.2.19 on 2023-06-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_auto_20230619_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_doc',
            name='project_doc',
            field=models.FileField(upload_to='project_doc', verbose_name='项目文件'),
        ),
    ]
