# Generated by Django 3.2.19 on 2023-06-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0020_alter_containerd_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='middleware',
            name='hostname',
            field=models.CharField(max_length=64, null=True, verbose_name='主机名'),
        ),
    ]
