# Generated by Django 3.2.19 on 2023-07-03 09:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0021_alter_middleware_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_doc',
            name='upload',
            field=models.FileField(default=0, upload_to='project_doc/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project_list',
            name='change_time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='修改时间'),
        ),
    ]
