# Generated by Django 3.2.19 on 2023-10-31 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0022_auto_20230703_0922'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrettyNum',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='name',
            new_name='user_name',
        ),
    ]
