# Generated by Django 3.2.19 on 2023-10-31 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0023_auto_20231031_0237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_name',
            new_name='name',
        ),
    ]
