# Generated by Django 3.2.19 on 2023-10-31 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0025_auto_20231031_0240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='account',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='depart',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='password',
        ),
    ]
