# Generated by Django 3.2.19 on 2023-10-31 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0027_userinfo_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app01.project_list', verbose_name='关联项目'),
        ),
    ]
