# Generated by Django 3.2.19 on 2024-01-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0030_remove_project_doc_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_doc',
            name='upload',
            field=models.FileField(default=1, upload_to='project_doc/'),
            preserve_default=False,
        ),
    ]
